use crate::acl::render_acls;
use crate::iface::render_interfaces as render_interfaces_l3;
use crate::iface_l2::render_interfaces as render_interfaces_l2;
use crate::routing::render_routing;
use crate::security::render_security_zones;
use crate::system::render_system;
use crate::vlan::render_vlans;
use netconv_core::ir::NetworkConfig;
use netconv_core::report::ConversionReport;
use netconv_core::traits::ConfigRenderer;

/// Прежнее имя, прежнее поведение — Eltex ESR (router/firewall).
/// Оставлен ради обратной совместимости с вызовами `--to eltex` без
/// `--profile` и со старыми интеграционными тестами. Эквивалентен
/// `EltexL3Renderer` (тот же render_body_l3, другое имя типа).
pub struct EltexRenderer;

/// L2-профиль: Eltex MES (управляемый коммутатор доступа/агрегации).
/// VLAN database, switchport/trunk, voice VLAN, storm-control, STP
/// portfast/bpduguard/bpdufilter. Routing, ACL, security zones — не
/// рендерятся: на плоском L2-свитче им нет соответствия.
pub struct EltexL2Renderer;

/// L3-профиль: Eltex ESR (router/firewall) — то же самое что
/// `EltexRenderer`, под именем, согласованным с VrpL2Renderer/
/// VrpL3Renderer из netconv-render-vrp.
pub struct EltexL3Renderer;

impl ConfigRenderer for EltexRenderer {
    type Error = EltexRenderError;

    fn render(
        &self,
        config: &NetworkConfig,
        report: &mut ConversionReport,
    ) -> Result<String, Self::Error> {
        Ok(render_body_l3(config, report))
    }

    fn vendor_name(&self) -> &str {
        "Eltex ESR"
    }
}

impl ConfigRenderer for EltexL3Renderer {
    type Error = EltexRenderError;

    fn render(
        &self,
        config: &NetworkConfig,
        report: &mut ConversionReport,
    ) -> Result<String, Self::Error> {
        Ok(render_body_l3(config, report))
    }

    fn vendor_name(&self) -> &str {
        "Eltex ESR"
    }
}

impl ConfigRenderer for EltexL2Renderer {
    type Error = EltexRenderError;

    fn render(
        &self,
        config: &NetworkConfig,
        report: &mut ConversionReport,
    ) -> Result<String, Self::Error> {
        Ok(render_body_l2(config, report))
    }

    fn vendor_name(&self) -> &str {
        "Eltex MES"
    }
}

/// L3-тело: то, что раньше было единственным render() у EltexRenderer.
/// Логика не менялась при рефакторинге — только вынесена в функцию,
/// чтобы EltexRenderer и EltexL3Renderer могли её разделять (тот же
/// паттерн, что render_body в netconv-render-vrp).
fn render_body_l3(config: &NetworkConfig, report: &mut ConversionReport) -> String {
    report.target_vendor = "Eltex ESR".to_string();

    let mut out = Vec::<String>::new();

    out.push("!".to_string());
    out.push("! Generated by netconv — review before applying".to_string());
    out.push("! Source: Cisco IOS → Target: Eltex ESR".to_string());
    out.push("!".to_string());
    out.push("! IMPORTANT: Eltex ESR requires security zones on all interfaces.".to_string());
    out.push("! All interfaces are placed in 'LAN' zone by default.".to_string());
    out.push("! Review zone assignments before applying — traffic will be blocked".to_string());
    out.push("! without correct firewall rules between zones.".to_string());
    out.push("!".to_string());
    out.push(String::new());

    // System: hostname, NTP, SNMP, users, SSH
    render_system(config, &mut out, report);

    // Security zones — обязательно до интерфейсов
    render_security_zones(config, &mut out, report);

    // Interfaces (ESR: security zone per interface, ip address, ACL, routing)
    render_interfaces_l3(config, &mut out, report);

    // ACL — тела списков, на которые ссылаются ip access-group на интерфейсах
    render_acls(config, &mut out, report);

    // Routing: static, OSPF, BGP
    render_routing(config, &mut out, report);

    // Unknown blocks
    if !config.unknown_blocks.is_empty() {
        out.push(String::new());
        out.push("!".to_string());
        out.push("! ============================================================".to_string());
        out.push("! НЕРАСПОЗНАННЫЕ КОМАНДЫ — требуют ручного переноса:".to_string());
        out.push("! ============================================================".to_string());
        for ub in &config.unknown_blocks {
            out.push(format!("! [line {}] {}", ub.line, ub.raw));
        }
    }

    // Platform specific
    if !config.platform_specific.is_empty() {
        out.push(String::new());
        out.push("! ============================================================".to_string());
        out.push("! ПЛАТФОРМО-СПЕЦИФИЧНЫЕ КОМАНДЫ (нет аналога на Eltex ESR):".to_string());
        out.push("! ============================================================".to_string());
        for ps in &config.platform_specific {
            out.push(format!("! [line {}] {}", ps.line, ps.raw));
        }
    }

    out.push(String::new());
    out.push("!".to_string());
    out.push("! Apply configuration:".to_string());
    out.push("! esr# commit".to_string());
    out.push("! esr# confirm".to_string());

    out.join("\n")
}

/// L2-тело: VLAN database + switchport-интерфейсы для Eltex MES.
/// Никакой security-zone логики (ESR-специфика, у плоского L2-свитча
/// её не бывает), никакого routing/ACL — это и есть весь смысл
/// разделения на профили.
fn render_body_l2(config: &NetworkConfig, report: &mut ConversionReport) -> String {
    report.target_vendor = "Eltex MES".to_string();

    let mut out = Vec::<String>::new();

    out.push("!".to_string());
    out.push("! Generated by netconv — review before applying".to_string());
    out.push("! Source: Cisco IOS → Target: Eltex MES".to_string());
    out.push("!".to_string());
    out.push("! NOTE: MES switch family (14xx/24xx vs 23xx/33xx/53xx) affects exact".to_string());
    out.push(
        "! VLAN-entry and port-numbering syntax — see per-item notes in the report.".to_string(),
    );
    out.push("!".to_string());
    out.push(String::new());

    render_system(config, &mut out, report);
    render_vlans(config, &mut out, report);
    render_interfaces_l2(config, &mut out, report);

    if !config.unknown_blocks.is_empty() {
        out.push(String::new());
        out.push("!".to_string());
        out.push("! ============================================================".to_string());
        out.push("! НЕРАСПОЗНАННЫЕ КОМАНДЫ — требуют ручного переноса:".to_string());
        out.push("! ============================================================".to_string());
        for ub in &config.unknown_blocks {
            out.push(format!("! [line {}] {}", ub.line, ub.raw));
        }
    }

    out.push(String::new());
    out.push("! write memory".to_string());

    out.join("\n")
}

#[derive(Debug)]
pub enum EltexRenderError {}
