use netconv_core::ir::NetworkConfig;
use netconv_core::report::ConversionReport;
use netconv_core::traits::ConfigRenderer;
use crate::system::render_system;
use crate::iface::render_interfaces;
use crate::routing::render_routing;
use crate::security::render_security_zones;

pub struct EltexRenderer;

impl ConfigRenderer for EltexRenderer {
    type Error = EltexRenderError;

    fn render(
        &self,
        config: &NetworkConfig,
        report: &mut ConversionReport,
    ) -> Result<String, Self::Error> {
        report.target_vendor = "Eltex ESR".to_string();

        let mut out = Vec::<String>::new();

        out.push("!".to_string());
        out.push("! Generated by netconv — review before applying".to_string());
        out.push("! Source: Cisco IOS → Target: Eltex ESR".to_string());
        out.push("!".to_string());
        out.push("! IMPORTANT: Eltex ESR requires security zones on all interfaces.".to_string());
        out.push("! All interfaces are placed in 'LAN' zone by default.".to_string());
        out.push("! Review zone assignments before applying — traffic will be blocked".to_string());
        out.push("! without correct firewall rules between zones.".to_string());
        out.push("!".to_string());
        out.push(String::new());

        // System: hostname, NTP, SNMP, users, SSH
        render_system(config, &mut out, report);

        // Security zones — обязательно до интерфейсов
        render_security_zones(config, &mut out, report);

        // Interfaces
        render_interfaces(config, &mut out, report);

        // Routing: static, OSPF, BGP
        render_routing(config, &mut out, report);

        // Unknown blocks
        if !config.unknown_blocks.is_empty() {
            out.push(String::new());
            out.push("!".to_string());
            out.push("! ============================================================".to_string());
            out.push("! НЕРАСПОЗНАННЫЕ КОМАНДЫ — требуют ручного переноса:".to_string());
            out.push("! ============================================================".to_string());
            for ub in &config.unknown_blocks {
                out.push(format!("! [line {}] {}", ub.line, ub.raw));
            }
        }

        // Platform specific
        if !config.platform_specific.is_empty() {
            out.push(String::new());
            out.push("! ============================================================".to_string());
            out.push("! ПЛАТФОРМО-СПЕЦИФИЧНЫЕ КОМАНДЫ (нет аналога на Eltex ESR):".to_string());
            out.push("! ============================================================".to_string());
            for ps in &config.platform_specific {
                out.push(format!("! [line {}] {}", ps.line, ps.raw));
            }
        }

        out.push(String::new());
        // ESR требует commit + confirm для применения конфигурации
        out.push("!".to_string());
        out.push("! Apply configuration:".to_string());
        out.push("! esr# commit".to_string());
        out.push("! esr# confirm".to_string());

        Ok(out.join("\n"))
    }

    fn vendor_name(&self) -> &str {
        "Eltex ESR"
    }
}

#[derive(Debug)]
pub enum EltexRenderError {}
