use netconv_core::ir::NetworkConfig;
use netconv_core::report::ConversionReport;
use netconv_core::traits::ConfigRenderer;
use crate::iface::render_interfaces;
use crate::routing::render_routing;
use crate::acl::render_acls;
use crate::nat::render_nat;
use crate::system::render_system;

pub struct VrpRenderer;

impl ConfigRenderer for VrpRenderer {
    type Error = VrpRenderError;

    fn render(
        &self,
        config: &NetworkConfig,
        report: &mut ConversionReport,
    ) -> Result<String, Self::Error> {
        report.target_vendor = "Huawei VRP".to_string();

        let mut out = Vec::<String>::new();

        // Заголовок
        out.push("#".to_string());
        out.push("# Generated by netconv — review before applying".to_string());
        out.push("# Source: Cisco IOS → Target: Huawei VRP".to_string());
        out.push("#".to_string());
        out.push(String::new());

        // Системные настройки
        render_system(config, &mut out, report);

        // Интерфейсы
        render_interfaces(config, &mut out, report);

        // ACL (до routing — может использоваться в route-policy)
        render_acls(config, &mut out, report);

        // Routing
        render_routing(config, &mut out, report);

        // NAT
        render_nat(config, &mut out, report);

        // Unknown blocks — комментируем в выводе
        if !config.unknown_blocks.is_empty() {
            out.push(String::new());
            out.push("# ============================================================".to_string());
            out.push("# НЕРАСПОЗНАННЫЕ КОМАНДЫ — требуют ручного переноса:".to_string());
            out.push("# ============================================================".to_string());
            for ub in &config.unknown_blocks {
                out.push(format!("# [line {}] {}", ub.line, ub.raw));
            }
        }

        out.push(String::new());
        out.push("return".to_string());

        Ok(out.join("\n"))
    }

    fn vendor_name(&self) -> &str {
        "Huawei VRP"
    }
}

#[derive(Debug)]
pub enum VrpRenderError {}
