use netconv_core::ir::NetworkConfig;
use netconv_core::report::ConversionReport;
use netconv_core::traits::ConfigRenderer;
use crate::iface::render_interfaces;
use crate::routing::render_routing;
use crate::acl::render_acls;
use crate::nat::render_nat;
use crate::system::render_system;
use crate::vlan::render_vlans;
use crate::scope::RenderScope;

/// Полный (не фильтрующий по домену) рендерер — прежнее поведение
/// `VrpRenderer` до разделения на l2/l3. Оставлен ради обратной
/// совместимости с вызовами `--to vrp` без `--profile` и со старыми
/// интеграционными тестами. Для новых пар предпочтительны
/// `VrpL2Renderer` / `VrpL3Renderer` — это и есть цель разделения:
/// не смешивать VLAN/switchport с routing/ACL/NAT в одном выводе.
pub struct VrpRenderer;

/// L2-профиль: VLAN, switchport/trunk, STP, voice VLAN, storm-control.
/// Целится в Huawei S-series (управляемый коммутатор). Routing, ACL,
/// NAT, HSRP из IR намеренно не рендерятся — их не бывает в конфиге
/// свитча доступа/агрегации.
pub struct VrpL2Renderer;

/// L3-профиль: IP-адресация, static/OSPF/BGP, ACL, NAT, HSRP→VRRP.
/// Целится в Huawei AR/NE (маршрутизатор). VLAN database и switchport
/// из IR намеренно не рендерятся — на роутере им нет соответствия.
pub struct VrpL3Renderer;

impl ConfigRenderer for VrpRenderer {
    type Error = VrpRenderError;

    fn render(&self, config: &NetworkConfig, report: &mut ConversionReport) -> Result<String, Self::Error> {
        Ok(render_body(config, report, RenderScope::All, "Huawei VRP"))
    }

    fn vendor_name(&self) -> &str {
        "Huawei VRP"
    }
}

impl ConfigRenderer for VrpL2Renderer {
    type Error = VrpRenderError;

    fn render(&self, config: &NetworkConfig, report: &mut ConversionReport) -> Result<String, Self::Error> {
        Ok(render_body(config, report, RenderScope::L2, "Huawei VRP (S-series, switch)"))
    }

    fn vendor_name(&self) -> &str {
        "Huawei VRP (S-series, switch)"
    }
}

impl ConfigRenderer for VrpL3Renderer {
    type Error = VrpRenderError;

    fn render(&self, config: &NetworkConfig, report: &mut ConversionReport) -> Result<String, Self::Error> {
        Ok(render_body(config, report, RenderScope::L3, "Huawei VRP (AR/NE, router)"))
    }

    fn vendor_name(&self) -> &str {
        "Huawei VRP (AR/NE, router)"
    }
}

/// Общее тело рендеринга для всех трёх режимов. Секции, не относящиеся
/// к scope, просто не вызываются — а не вызываются и потом дропаются,
/// как раньше молча делал EltexRenderer для L2 на ESR.
fn render_body(config: &NetworkConfig, report: &mut ConversionReport, scope: RenderScope, vendor_label: &str) -> String {
    report.target_vendor = vendor_label.to_string();

    let mut out = Vec::<String>::new();

    // Заголовок
    out.push("#".to_string());
    out.push("# Generated by netconv — review before applying".to_string());
    out.push(format!("# Source: Cisco IOS → Target: {}", vendor_label));
    out.push("#".to_string());
    out.push(String::new());

    // Системные настройки — общие для L2 и L3
    render_system(config, &mut out, report);

    // VLAN database — только для L2, должна быть ДО интерфейсов
    if scope.wants_l2() {
        render_vlans(config, &mut out, report);
    }

    // Интерфейсы — сами фильтруют L2/L3-специфичные блоки по scope
    render_interfaces(config, &mut out, report, scope);

    // ACL / Routing / NAT — только для L3
    if scope.wants_l3() {
        render_acls(config, &mut out, report);
        render_routing(config, &mut out, report);
        render_nat(config, &mut out, report);
    }

    // Unknown blocks — комментируем в выводе, независимо от scope
    if !config.unknown_blocks.is_empty() {
        out.push(String::new());
        out.push("# ============================================================".to_string());
        out.push("# НЕРАСПОЗНАННЫЕ КОМАНДЫ — требуют ручного переноса:".to_string());
        out.push("# ============================================================".to_string());
        for ub in &config.unknown_blocks {
            out.push(format!("# [line {}] {}", ub.line, ub.raw));
        }
    }

    out.push(String::new());
    out.push("return".to_string());

    out.join("\n")
}

#[derive(Debug)]
pub enum VrpRenderError {}
